### ISSUE TITLE
Detecting new peer added

### ISSUE THREAD

**Issue by MichealSBingham** [insidegui/MultipeerKit#21]
Hi,  @insidegui 

How do  I actually use the closure to detect a new peer was added?

I try 

`transceiver.peerAdded { peer in
 
}`

But it gives a syntax error

**Comment by insidegui** [comment]
You have to set the closure property, such as:

```swift
myTransceiver.peerAdded = { peer in
    // ...
}
```

[Check out the examples](https://github.com/insidegui/MultipeerKit/tree/main/example) to see how it's used. If you have other general code-level questions about the library, you can [use the discussions section here](https://github.com/insidegui/MultipeerKit/discussions).
